### ISSUE TITLE
Fov changer было бы не плохо добавить 

### ISSUE THREAD

**Issue by Mozgopravin** [pa1n-dev/nixware_x64#12]
Никсер я знаю что ты на твинке падла разбань меня на форуме пж я больше не буду кидать ратники школьникам 
![d864c66b963f56affb8588c8e5a5eca2](https://github.com/pa1n-dev/nixware_x64/assets/74500024/491f5149-4509-439d-bf7f-fe27c5c311a5)

**Comment by pa1n-dev** [comment]
завтра опубликую
