### ISSUE TITLE
features , not a bug report

### ISSUE THREAD

**Issue by theREALabdul2** [pa1n-dev/nixware_x64#17]
hello , it would be amazing if you could add these things: 

- configs 
 
- friends list 
   the ability to add people from a list of players in a server for aimbot to not target , and to also show it on ESP.
- custom loading screen update
   the ability to change the image in the custom loading screen from a link , such as a discord link or a imgur link. 
-  lua executor update
    the ability to change a lua file's code within the client
     
 best wishes

**Comment by pa1n-dev** [comment]
Thanks a lot.
I will try to implement these ideas

**Comment by pa1n-dev** [comment]
Made 1 and 3
