### ISSUE TITLE
GLUA Loader

### ISSUE THREAD

**Issue by DarkSide1337228** [pa1n-dev/nixware_x64#21]
возьми лучше asuna "https://github.com/shockpast/asuna-gmod" там и нетлоггер и scripthook сразу есть, сделай просто menubar как в метхе и заебок будет!
если сделаешь так, то вообще с кайфом будет, лично приеду отсосу

**Comment by shockpast** [comment]
в текущей версии асуне нет нетлогерра (asuna - logger, это просто название для консольки где все обычные логи собираются), а так я уже сделал рабочую версию net логгера и http логгера, правда я всю ночь из-за этого не спал, выложу когда будет время
