### ISSUE TITLE
VC++ Directories

### ISSUE THREAD

**Issue by Ceypi** [pa1n-dev/nixware_x64#22]
So i have DirectX and also freetype and have also compiled freetype to win64 but this doesn't seem to be the correct way to do this.

Could someone enlighten me on what the proper directories/solution dependencies are?

**Comment by Ceypi** [comment]
Include  | C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\Include;D:\Freetype\include;$(IncludePath)

Library  | C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\Lib\x64;D:\Freetype\objs\x64\Release;$(LibraryPath)

This is what i have in my directories.

**Comment by pa1n-dev** [comment]
Hello, if you have problems with freetype then you need to add them to .lib
Also, I once had problems a long time ago with the fact that the dependencies were on different disks

[Freetype.zip](https://github.com/pa1n-dev/nixware_x64/files/15407037/Freetype.zip)

**Comment by Ceypi** [comment]
Perfect! , Thanks for the quick reply and this does indeed fix the problems with building it. 
<3
