### ISSUE TITLE
Netvars

### ISSUE THREAD

**Issue by Ceypi** [pa1n-dev/nixware_x64#23]
Ok so im writing up a spectator list.

This is my c_base_entity code right now.  ( doesnt compile obviously ) 
How would you approach @pa1n-dev ?

I'm new to C++ and don't exactly understand how you got the index numbers. 

	c_base_entity* get_observer_target()
	{
		uint32_t m_hObserverTarget = *(uint32_t*)((uintptr_t)this + 0x2c88);
		return interfaces::entity_list->get_entity_from_handle(m_hObserverTarget);
	}

**Comment by Ceypi** [comment]
Was looking at gmodsdk,cranium and CFF for information about their ways of getting netvars but they use macro's instead of the system that is inplace in nixware

**Comment by Ceypi** [comment]
Got it to work.
	c_base_entity* get_observer_target() {
		using fn = void* (__fastcall*)(void*);
		static fn f;
		if (!f)
			f = (fn)memory::pattern_scanner("client.dll", "40 53 48 83 EC 20 48 39 0D ? ? ? ? 48 8B D9 75 26");
		return (c_base_entity*)f(this);
	}

**Comment by pa1n-dev** [comment]
Thank you very much for your contribution to the project
