### ISSUE TITLE
[BUG] Can't build

### ISSUE THREAD

**Issue by Toaaa** [pa1n-dev/nixware_x64#25]
Can't build pls help: `Cannot open include file: 'd3dx9.h': No such file or directory. `
I already tried to download the [DirectX SDK (June 2010)](https://www.microsoft.com/en-us/download/details.aspx?id=6812). However, Microsoft no longer lets you download it.

![](https://i.toaaa.de/i/oq13c.png)

**Comment by pa1n-dev** [comment]
install DirectX SDK and add 
![image](https://github.com/pa1n-dev/nixware_x64/assets/74207477/0de28ef0-e578-4362-8753-00831c5d8f37)

**Comment by Toaaa** [comment]
> install DirectX SDK and add

How and Where to download?

**Comment by pa1n-dev** [comment]
https://www.[microsoft.com/ru-ru/download/details.aspx?id=6812](https://www.microsoft.com/ru-ru/download/details.aspx?id=6812)

**Comment by pa1n-dev** [comment]
![image](https://github.com/pa1n-dev/nixware_x64/assets/74207477/9a1fbc84-69e3-4851-85df-f79c3e981f64)
click on download 
https://www.microsoft.com/en-us/download/details.aspx?id=6812
