### ISSUE TITLE
config system

### ISSUE THREAD

**Issue by inserti550** [pa1n-dev/nixware_x64#28]
когда я использовал твой чит я заметил что нету конфиг системы, не очень удобно настраивать все каждый раз сначала, я не сильно силен в C++ но так или иначе я написал кфг систему под твой чит. Говнокод сплошной но так или иначе тема рабочая
[nixware_x64.zip](https://github.com/user-attachments/files/15803131/nixware_x64.zip)
также было бы неплохо добавить кейбинд на invert yaw иногда нужно, это сделать дело 5-ти минут если понимать что и как

**Comment by pa1n-dev** [comment]
завтра опубликую
