### ISSUE TITLE
[BUG] Instant crash on injection

### ISSUE THREAD

**Issue by Aiko-Suzuki** [pa1n-dev/nixware_x64#30]
**Description of the problem**
Game instently silent crash on injection

**Expected behavior**
game to not crash

**Actual behavior**
just crash

**Comment by pa1n-dev** [comment]
Check gmod is x64 chromium.
Also try injecting via process hacker

**Comment by Aiko-Suzuki** [comment]
Already on chronium x64 and am injecting using extreme injector 3.7.3

**Comment by pa1n-dev** [comment]
My friends and I do not get any problems with injection, can you describe the problem in more detail?

**Comment by Aiko-Suzuki** [comment]
Gonna try with process hacker tomorrow but right now the game just silently crash no error or anything just close.

**Comment by Aiko-Suzuki** [comment]
https://github.com/pa1n-dev/nixware_x64/assets/42787030/ed39fb6f-1702-4f21-b7c5-2362dbcd8f13

**Comment by Aiko-Suzuki** [comment]
using windbg i can see a this after injecting
```
(61c4.3114): Access violation - code c0000005 (!!! second chance !!!)
eax=15e50000 ebx=00000000 ecx=7684d8a0 edx=4855f910 esi=15e50002 edi=7684d8a0
eip=7788a290 esp=4855f8dc ebp=4855f8e0 iopl=0         nv up ei pl nz na pe nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00010206
ntdll!RtlInitUnicodeStringEx+0x20:
7788a290 668b08          mov     cx,word ptr [eax]        ds:002b:15e50000=????
```

**Comment by Aiko-Suzuki** [comment]
now i can inject without crash but once loading in a game / server game crash

**Comment by Aiko-Suzuki** [comment]
commenting those lines seems to fix the problem
in `hooks\handles\hl_client\create_move.h`
```
	/*bool send_packet = fakelags::run(cmd);
	antiaim::run(cmd, send_packet);
	animfix::run(cmd, send_packet);*/
	/*fakelags::apply(send_packet);*/
```

**Comment by pa1n-dev** [comment]
> now i can inject without crash but once loading in a game / server game crash the error is
> 
> ```
> nixware!c_hl2mp_player_anim_state::operator=+0x50:
> 00007ffb`1687dd10 0fb609          movzx   ecx,byte ptr [rcx] ds:00000000`461c4000=??
> ```

this is another crash because a hidden update for gmod has been released
